defaults:
  - base_config
  - override hydra/job_logging: custom-simplest
  - _self_

hydra:
  run:
    dir: ./output/${exp_id}
  output_subdir: eval-${now:%Y-%m-%d_%H-%M-%S}-hydra

exp_id: ${model}
dataset: javisbench
duration_s: 4.0

# for inference, this is the per-GPU batch size
batch_size: 1
output_name: null